#### Don't forget that you will also need the default.conf, html.tar.gz,and nginx.conf files in the files folder.
#### $ docker image build --file <path_to_Dockerfile> --tag <REPOSITORY>:<TAG> .
#### $docker container run -d --name dockerfile-example -p 8080:80 local:dockerfile-example

FROM alpine:latest
LABEL maintainer="Russ McKendrick <russ@mckendrick.io>"
LABEL description="This example Dockerfile installs NGINX."
RUN apk add --update nginx && \
 rm -rf /var/cache/apk/* && \
 mkdir -p /tmp/nginx/

COPY files/nginx.conf /etc/nginx/nginx.conf
COPY files/default.conf /etc/nginx/conf.d/default.conf
ADD files/html.tar.gz /usr/share/nginx/

EXPOSE 80/tcp

ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
